# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

commands:
  destroy_environment:
    steps:
      - run:
          when: on_fail
          name: destroy environment
          command: aws cloudformation delete-stack --stack-name prod-${CIRCLE_WORKFLOW_ID}

jobs:
  create_infra:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      # - add_ssh_keys:
      #     fingerprints: ["8a:42:7a:17:c4:77:f5:51:d9:b4:a9:cf:dd:71:70:c2"]
      # - run:
      #     name: Install dependencies
      #     command: |
      #       apk add --update ansible # install the dependencies needed for your playbook
      # - run:
      #     name: Configure server
      #     command: |
      #       ansible-playbook -i inventory playbook.yml
      - run: 
          name: create CF stack
          command: aws cloudformation deploy --template-file template.yml --stack-name prod-${CIRCLE_WORKFLOW_ID}
      - run:
          name: force an error
          command: exit 1
      - destroy_environment

# Orchestrate or schedule a set of jobs
workflows:
  create_infrastructure:
    jobs:
      - create_infra
